// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BangazonBE.Migrations
{
    [DbContext(typeof(BangazonBEDbContext))]
    partial class BangazonBEDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BangazonBE.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Type = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            Type = "Electronics"
                        },
                        new
                        {
                            CategoryId = 3,
                            Type = "Grocery"
                        },
                        new
                        {
                            CategoryId = 4,
                            Type = "Beauty"
                        },
                        new
                        {
                            CategoryId = 5,
                            Type = "Clothing"
                        });
                });

            modelBuilder.Entity("BangazonBE.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 601,
                            CreatedAt = new DateTime(2023, 8, 28, 18, 36, 47, 391, DateTimeKind.Local).AddTicks(4340),
                            OrderStatusId = 1,
                            UserId = 102
                        },
                        new
                        {
                            OrderId = 602,
                            CreatedAt = new DateTime(2023, 8, 28, 18, 36, 47, 391, DateTimeKind.Local).AddTicks(4390),
                            OrderStatusId = 2,
                            UserId = 102
                        },
                        new
                        {
                            OrderId = 603,
                            CreatedAt = new DateTime(2023, 8, 28, 18, 36, 47, 391, DateTimeKind.Local).AddTicks(4400),
                            OrderStatusId = 4,
                            UserId = 104
                        },
                        new
                        {
                            OrderId = 604,
                            CreatedAt = new DateTime(2023, 8, 28, 18, 36, 47, 391, DateTimeKind.Local).AddTicks(4400),
                            OrderStatusId = 6,
                            UserId = 104
                        },
                        new
                        {
                            OrderId = 605,
                            CreatedAt = new DateTime(2023, 8, 28, 18, 36, 47, 391, DateTimeKind.Local).AddTicks(4400),
                            OrderStatusId = 5,
                            UserId = 105
                        });
                });

            modelBuilder.Entity("BangazonBE.Models.OrderProduct", b =>
                {
                    b.Property<int>("OrderProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderProductId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("OrderProductId");

                    b.ToTable("OrderProduct");

                    b.HasData(
                        new
                        {
                            OrderProductId = 501,
                            OrderId = 601,
                            ProductId = 403
                        },
                        new
                        {
                            OrderProductId = 502,
                            OrderId = 602,
                            ProductId = 404
                        },
                        new
                        {
                            OrderProductId = 503,
                            OrderId = 603,
                            ProductId = 401
                        },
                        new
                        {
                            OrderProductId = 504,
                            OrderId = 604,
                            ProductId = 405
                        },
                        new
                        {
                            OrderProductId = 505,
                            OrderId = 605,
                            ProductId = 402
                        });
                });

            modelBuilder.Entity("BangazonBE.Models.OrderStatus", b =>
                {
                    b.Property<int>("OrderStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderStatusId");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            OrderStatusId = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            OrderStatusId = 2,
                            Status = "In Progress"
                        },
                        new
                        {
                            OrderStatusId = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            OrderStatusId = 5,
                            Status = "Shipped"
                        },
                        new
                        {
                            OrderStatusId = 6,
                            Status = "Delivered"
                        });
                });

            modelBuilder.Entity("BangazonBE.Models.PaymentType", b =>
                {
                    b.Property<int>("PaymentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentTypeId"));

                    b.Property<int>("CardNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CardTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTypes");

                    b.HasData(
                        new
                        {
                            PaymentTypeId = 301,
                            CardNumber = 3526,
                            CardTypeName = "Visa"
                        },
                        new
                        {
                            PaymentTypeId = 302,
                            CardNumber = 2391,
                            CardTypeName = "Visa"
                        },
                        new
                        {
                            PaymentTypeId = 303,
                            CardNumber = 5364,
                            CardTypeName = "Giftcard"
                        },
                        new
                        {
                            PaymentTypeId = 304,
                            CardNumber = 3518,
                            CardTypeName = "Discover"
                        },
                        new
                        {
                            PaymentTypeId = 305,
                            CardNumber = 6952,
                            CardTypeName = "Mastercard"
                        },
                        new
                        {
                            PaymentTypeId = 306,
                            CardNumber = 2986,
                            CardTypeName = "American Express"
                        },
                        new
                        {
                            PaymentTypeId = 307,
                            CardNumber = 1628,
                            CardTypeName = "Mastercard"
                        },
                        new
                        {
                            PaymentTypeId = 308,
                            CardNumber = 4352,
                            CardTypeName = "American Express"
                        });
                });

            modelBuilder.Entity("BangazonBE.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 401,
                            CategoryId = 2,
                            Description = "Classic original red and blue console in perfect untouched condition",
                            Name = "Nintendo Switch",
                            ProductPrice = 300m,
                            Quantity = 3,
                            UserId = 103
                        },
                        new
                        {
                            ProductId = 402,
                            CategoryId = 4,
                            Description = "MAC Beauty Concealer in shade 3 for ivory skin-tone",
                            Name = "MAC Consealer Shade 3",
                            ProductPrice = 12.99m,
                            Quantity = 10,
                            UserId = 101
                        },
                        new
                        {
                            ProductId = 403,
                            CategoryId = 5,
                            Description = "1985 Vintage Def Leppard tee in worn-gray with front and back decal, one of a kind",
                            Name = "Def Leppard Vintage Tshirt",
                            ProductPrice = 24.99m,
                            Quantity = 1,
                            UserId = 101
                        },
                        new
                        {
                            ProductId = 404,
                            CategoryId = 1,
                            Description = "Four Mid-Century Modern Dining Chairs In Dark Walnut Finish",
                            Name = "Dining Chairs",
                            ProductPrice = 50m,
                            Quantity = 4,
                            UserId = 103
                        },
                        new
                        {
                            ProductId = 405,
                            CategoryId = 1,
                            Description = "Golden Pothos rooted propogations in small planters. Need gone NOW",
                            Name = "Pothos Propagations",
                            ProductPrice = 3.78m,
                            Quantity = 24,
                            UserId = 101
                        });
                });

            modelBuilder.Entity("BangazonBE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSeller")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 101,
                            Address = "70 Studebaker Street",
                            Email = "pavel@outlook.com",
                            FirstName = "Prianka",
                            IsSeller = true,
                            LastName = "Pavel"
                        },
                        new
                        {
                            UserId = 102,
                            Address = "7589 Courtland Ave",
                            Email = "keutzer@gmail.com",
                            FirstName = "Abraham",
                            IsSeller = false,
                            LastName = "Keutzer"
                        },
                        new
                        {
                            UserId = 103,
                            Address = "485 Laurel St",
                            Email = "honestgoods@me.com",
                            FirstName = "Honest",
                            IsSeller = true,
                            LastName = "Goods"
                        },
                        new
                        {
                            UserId = 104,
                            Address = "5698 Grove Lane",
                            Email = "mleary@icloud.com",
                            FirstName = "Megan",
                            IsSeller = false,
                            LastName = "Leary"
                        },
                        new
                        {
                            UserId = 105,
                            Address = "10 South Harrison Dr",
                            Email = "gpetersen@yahoo.com",
                            FirstName = "George",
                            IsSeller = false,
                            LastName = "Petersen"
                        });
                });

            modelBuilder.Entity("BangazonBE.Models.UserPayment", b =>
                {
                    b.Property<int>("UserPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserPaymentId"));

                    b.Property<int>("PaymentTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserPaymentId");

                    b.HasIndex("PaymentTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPayments");

                    b.HasData(
                        new
                        {
                            UserPaymentId = 201,
                            PaymentTypeId = 302,
                            UserId = 101
                        },
                        new
                        {
                            UserPaymentId = 202,
                            PaymentTypeId = 303,
                            UserId = 102
                        },
                        new
                        {
                            UserPaymentId = 203,
                            PaymentTypeId = 306,
                            UserId = 103
                        },
                        new
                        {
                            UserPaymentId = 204,
                            PaymentTypeId = 308,
                            UserId = 104
                        },
                        new
                        {
                            UserPaymentId = 205,
                            PaymentTypeId = 304,
                            UserId = 105
                        });
                });

            modelBuilder.Entity("BangazonBE.Models.Order", b =>
                {
                    b.HasOne("BangazonBE.Models.OrderStatus", "OrderStatus")
                        .WithMany()
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BangazonBE.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BangazonBE.Models.PaymentType", b =>
                {
                    b.HasOne("BangazonBE.Models.User", null)
                        .WithMany("PaymentTypes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("BangazonBE.Models.UserPayment", b =>
                {
                    b.HasOne("BangazonBE.Models.PaymentType", "PaymentType")
                        .WithMany()
                        .HasForeignKey("PaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BangazonBE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BangazonBE.Models.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PaymentTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
